### ISSUE TITLE
Causes Mod Menu button not to work

### ISSUE THREAD

**Issue by wafflecoffee** [Lucaslah/no-report-button#1]
Had two setups, one with NRB and one without.

With (unexpected behaviour): https://user-images.githubusercontent.com/60205699/186473538-7d2e1def-bc4b-4326-a153-1d25ba87ad31.mp4
Without (expected behaviour): https://user-images.githubusercontent.com/60205699/186472685-0d3c90f2-a8df-4c29-a572-92fdaf92696c.mp4

**Comment by Lucaslah** [comment]
I have confirmed this bug, Ill try and fix it as soon as possible

**Comment by Lucaslah** [comment]
@wafflecoffee if you want to download the new version before it is approved on curseforge you can download it here: https://github.com/Lucaslah/no-report-button/releases/download/v1.2.0/no-report-button-1.2.0.jar

**Comment by wafflecoffee** [comment]
As long as it's uploaded to Modrinth, I am an admin there after all :)

**Comment by Lucaslah** [comment]
Alright just uploaded to Modrinth now
