### ISSUE TITLE
Social Interaction can still be opened using TAB + Enter.

### ISSUE THREAD

**Issue by Kichura** [Lucaslah/no-report-button#3]
Title says it; This allows the button to be interacted with anyways despite it being replaced back with the grayed out "Open to LAN" button on 3rd-party servers / realms.

[Clip for it is here.](https://user-images.githubusercontent.com/68134602/194564035-80846ffd-130f-4137-b826-9c8b65436168.mp4)

**Comment by Lucaslah** [comment]
Hi, this screen? 
![10 6 2022](https://user-images.githubusercontent.com/47047328/194421105-65a6ea20-5469-4d3d-93f3-92043244d508.png)


I don't see any report button, I will be happy to fix this but I don't know where you mean.

**Comment by Kichura** [comment]
Yes that one - i made a typo on my OP comment.

**Comment by Lucaslah** [comment]
Thanks for this video, I see what you mean now. I will get started on fixing it as soon as I get a chance.

**Comment by Lucaslah** [comment]
Fixed, I will upload the new version today.

**Comment by Lucaslah** [comment]
New version has been upload to Modrinth and Curseforge.

**Comment by Kichura** [comment]
alright, thank you.
