### ISSUE TITLE
Mod is broken when using 1.19.3

### ISSUE THREAD

**Issue by DreamStanMan** [Lucaslah/no-report-button#4]
The Player Reporting button still appears on 1.19.3 using the latest version of the mod.

**Comment by Lucaslah** [comment]
Hi, I will look into this today.

**Comment by Lucaslah** [comment]
@DreamStanMan I have updated for 1.19.3.

I have updated on modrinth, but you will have to wait for it to be approved on curseforge if you want to download it there.

**Comment by DreamStanMan** [comment]
Thank you!
